### ISSUE TITLE
Component Logelevel options (Feature request)

### ISSUE THREAD

**Issue by dervogt** [albertogeniola/meross-homeassistant#120]
Not sure if I missed this on previous discussions, I remember to have seen one during the alpha phase before this issue list got cleaned up:

would it be possible to add loglevel options to the component which can either be approached via config flow in HA or can be set in the configuration.yaml ?

RIght now the log is pretty talky and if you run HA without complete hard restart on your docker, the log can be quite convoluted with messages and I had a few days on which the Logfile of HA grew into the GB range as on docker, if you don't restart the whole container and just make the "internal restart" it is not purging the previous logfile........

**Comment by albertogeniola** [comment]
Hi @dervogt ,

so far you should be able to control the loglevels via homeassistant configuration file.
For instance, if you wanted to limit meross_iot log entries to severity equal or greater than "WARNING", just edit file `configuration.yaml` as follows:

```yaml
# ... omissis ...
logger:
  default: info  # set everything else at INFO
  logs:
    meross_iot.manager: warning  # Set meross_iot.manager to WARNING
    custom_components.meross_cloud: warning
# ... omissis ...
```
