### ISSUE TITLE
my switchs meross becomes unavailable every day

### ISSUE THREAD

**Issue by yepp31** [albertogeniola/meross-homeassistant#269]
have 7 sockets connected and since update 1.1.4 I lose the connection of all my sockets every day. i uninstalled and reinstalled the addon but still the same problem.

Home Assistant 2021.9.3
rpi4 64bits

```

**Comment by Flameboy42** [comment]
Same. Only have two sockets. They were working for a week there, but nothing over the last two days.

**Comment by zappy16** [comment]
Same. Only have the MSG100 garage door opener and constantly have to reload the integration. Home Assistant 2021.9.3, rpi4 docker

**Comment by unlucio** [comment]
same here and for months.
homeassistant's logs are littered in these errors:

```python
2021-09-09 11:07:44 ERROR (MainThread) [meross_iot.manager] An error occurred while executing push notification handling for <meross_iot.model.push.online.OnlinePushNotification object at 0xa6e7f1a8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 784, in _handle_and_dispatch_push_notification
    await handler(
  File "/config/custom_components/meross_cloud/sensor.py", line 482, in platform_async_add_entities
    await manager.async_device_discovery(push_notification.namespace == Namespace.HUB_ONLINE,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 333, in async_device_discovery
    http_devices = await self._http_client.async_list_devices()
  File "/usr/local/lib/python3.9/site-packages/meross_iot/http_api.py", line 318, in async_list_devices
    result = await MerossHttpClient._async_authenticated_post(url, {}, cloud_creds=self._cloud_creds, http_proxy=self._http_proxy)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/http_api.py", line 230, in _async_authenticated_post
    raise AuthenticatedPostException("Failed request to API. Response code: %s" % str(response.status))
meross_iot.model.http.exception.AuthenticatedPostException: Failed request to API. Response code: 429
```

**Comment by Leivaster** [comment]
Me too

> same here and for months.
> homeassistant's logs are littered in these errors:
> 
> ```python
> 2021-09-09 11:07:44 ERROR (MainThread) [meross_iot.manager] An error occurred while executing push notification handling for <meross_iot.model.push.online.OnlinePushNotification object at 0xa6e7f1a8>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 784, in _handle_and_dispatch_push_notification
>     await handler(
>   File "/config/custom_components/meross_cloud/sensor.py", line 482, in platform_async_add_entities
>     await manager.async_device_discovery(push_notification.namespace == Namespace.HUB_ONLINE,
>   File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 333, in async_device_discovery
>     http_devices = await self._http_client.async_list_devices()
>   File "/usr/local/lib/python3.9/site-packages/meross_iot/http_api.py", line 318, in async_list_devices
>     result = await MerossHttpClient._async_authenticated_post(url, {}, cloud_creds=self._cloud_creds, http_proxy=self._http_proxy)
>   File "/usr/local/lib/python3.9/site-packages/meross_iot/http_api.py", line 230, in _async_authenticated_post
>     raise AuthenticatedPostException("Failed request to API. Response code: %s" % str(response.status))
> meross_iot.model.http.exception.AuthenticatedPostException: Failed request to API. Response code: 429
> ```

Me too.
I reload the integration with 5 switches and after a while they all become unavailable. Same error as Unlucio

**Comment by CheekyMonkeyPo** [comment]
+1 for the above. Just seems to randomly drop. Reload manually and all ok again.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 919, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout, loop=self._loop)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 365, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/mixins/electricity.py", line 43, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
  File "/usr/local/lib/python3.9/site-packages/meross_iot/controller/device.py", line 281, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 838, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 903, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
  File "/usr/local/lib/python3.9/site-packages/meross_iot/manager.py", line 934, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError

**Comment by andornaut** [comment]
I have the same experience. I have one garage switch, which seems to become unavailable multiple times per day.

I've used this automation to improve the situation somewhat:
```
- alias: Reload Meross when unavailable
  description: Reload the Meross Smart Garage Door service when the connection becomes unavailable. Retry every minute for 1 hours.
  trigger:
    - platform: state
      entity_id: cover.garage_msg100_main_channel
      to: unavailable
      for: 00:00:30
  action:
    - repeat:
        while:
          - condition: state
            entity_id: cover.garage_msg100_main_channel
            state: unavailable
          - condition: template
            value_template: "{{ repeat.index < 60 }}" # 1-indexed
        sequence:
          - service: homeassistant.reload_config_entry
            target:
              entity_id: cover.garage_msg100_main_channel
          - delay:
              minutes: 1
  mode: single
```
