### ISSUE TITLE
cover.toggle on an open garage goes to transient state opening, requiring me to toggle a 2nd time to actually close

### ISSUE THREAD

**Issue by prashker** [albertogeniola/meross-homeassistant#501]
**Describe the bug**
I routinely open and close my garage using a widget on Android that calls cover.toggle. The first time I toggle on my open garage (state=Open) it switches to (state=Opening) with no action. Clicking toggle again works.

![image](https://github.com/albertogeniola/meross-homeassistant/assets/1865169/1c862e13-8ddd-43b1-87ee-8c9f4ffdd5e5)

**Your environment**
HomeAssistant version: 2024.5.3
Hassio Version (if applicable): N/A
Hardware environment:  msg100 4.0.0 by Meross Firmware: 4.2.12
Meross Home Assistant plugin version: 1.3.2

**Logs taken when the issue happened**
Not sure how to get more in depth logs, but attached screenshot which shows Logbook reflecting my actions

**Comment by prashker** [comment]
As additional details (I think relevant enough for a comment)

From a closed garage (fully controlled via HASS) 🟢:
* Opening via cover.toggle works (state=Closed->Opening->Opened)
* Closing via cover.toggle works (state=Opened->Closing->Closed)

From a closed garage (hybrid approach) 🔴:
* Opening via garages OEM remote works (state=Closed->Opened)
* Closing via cover.toggle fails first time (state=Opened->Opening) **does not close**
* Have to click cover.toggle a 2nd time (state=Opening->Closing->Closed)

**Comment by prashker** [comment]
For anyone visiting from the future, I managed to workaround this issue by setting up an automation to close my garage when it goes from "open" to "opening" (a transition that shouldn't be normally possible)

Working well for past few days!

```
alias: GARAGE - Open to Opening bug
description: Auto close when bug encountered
trigger:
  - platform: state
    entity_id:
      - cover.garage_msg100_main_channel
    from: open
    to: opening
condition: []
action:
  - service: cover.close_cover
    metadata: {}
    data: {}
    target:
      entity_id: cover.garage_msg100_main_channel
mode: single

```

Hope this helps in the interim!
